# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Docker@2
  inputs:
    repository: '719353466243.dkr.ecr.us-east-1.amazonaws.com/vms/k8s-poc'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '-t dotnetdeploypoc .'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS Account'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'dotnetdeploypoc'
    repositoryName: '719353466243.dkr.ecr.us-east-1.amazonaws.com/vms/k8s-poc'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "listing local bin----------------------------------"
      ls bin
     